1. Load in the dataset (starbucks_drinkMenu_expanded.csv), calling it drinks_content, and      then briefly explore it, printing out: first 5 rows, last 5 rows, and then all of the      data. Find out the dimensions of the data (number of rows and columns) and the column      names.

In [1]:
import pandas as pd

drinks_content = pd.read_csv("data/starbucks_drinkMenu_expanded.csv")

In [4]:
drinks_content.head(5)

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [5]:
drinks_content.tail(5)

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
237,Frappuccino® Blended Crème,Strawberries & Crème (Without Whipped Cream),Soymilk,320,3 2,0.4,0.0,0,250,67,1,64,5.0,6%,8%,20%,10%,0
238,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Tall Nonfat Milk,170,0.1,0.1,0.0,0,160,39,0,38,4.0,6%,0%,10%,0%,0
239,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Whole Milk,200,3.5,2.0,0.1,10,160,39,0,38,3.0,6%,0%,10%,0%,0
240,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Soymilk,180,1.5,0.2,0.0,0,160,37,1,35,3.0,4%,0%,10%,6%,0
241,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande Nonfat Milk,240,0.1,0.1,0.0,5,230,56,0,55,5.0,8%,0%,15%,0%,0

In [13]:
drinks_content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Beverage_category          242 non-null    object
 1   Beverage                   242 non-null    object
 2   Beverage_prep              242 non-null    object
 3   Calories                   242 non-null    int64
 4    Total Fat (g)             242 non-null    object
 5   Trans Fat (g)              242 non-null    float64
 6   Saturated Fat (g)          242 non-null    float64
 7    Sodium (mg)               242 non-null    int64
 8    Total Carbohydrates (g)   242 non-null    int64
 9   Cholesterol (mg)           242 non-null    int64
 10   Dietary Fibre (g)         242 non-null    int64
 11   Sugars (g)                242 non-null    int64
 12   Protein (g)               242 non-null    float64
 13  Vitamin A (% DV)           242 non-null    object
 14  Vitamin C (% DV)           242 non-null    object
 15   Calcium (% DV)            242 non-null    object
 16  Iron (% DV)                242 non-null    object
 17  Caffeine (mg)              241 non-null    object
dtypes: float64(3), int64(6), object(9)
memory usage: 34.2+ KB

2. We're going to be looking at the number of Calories in each drink. Calculate some quick    summary statistics (e.g. the mean, the maximum and minimum).

In [12]:
drinks_content["Calories"].describe()

count    242.000000
mean     193.871901
std      102.863303
min        0.000000
25%      120.000000
50%      185.000000
75%      260.000000
max      510.000000
Name: Calories, dtype: float64

3. Select the variables Beverage_category, Beverage, Beverage prep and Calories from the drinks_content data frame,    and assign the selected columns to a new data frame called drinks. Check if there are any missing values            anywhere in the data, and drop any rows containing them if there are.

In [19]:
drinks = drinks_content[["Beverage_category", "Beverage", "Beverage_prep", "Calories"]]

In [21]:
drinks.isnull().any()

Beverage_category    False
Beverage             False
Beverage_prep        False
Calories             False
dtype: bool

4. In your drinks dataframe create a new variable (column) called calorie_diff, which stores the difference between    135 calories (135 calories = 10 cubes of sugar!) and the calories in each drink. (Hint: you’ll want to subtract    the calories from 135 to see which drinks have more or less than 10 cubes of sugar).

In [22]:
drinks["calorie_diff"] = drinks["Calories"] - 135

/var/folders/p_/pzrkf0_s659_ff3y95gqjvbc0000gn/T/ipykernel_49539/3501098156.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drinks["calorie_diff"] = drinks["Calories"] - 135

5. Summarise the mean number of calories in each beverage category.

In [28]:
drinks.groupby("Beverage_category").mean("Calories")

                                     Calories  calorie_diff
Beverage_category
Classic Espresso Drinks            140.172414      5.172414
Coffee                               4.250000   -130.750000
Frappuccino® Blended Coffee        276.944444    141.944444
Frappuccino® Blended Crème         233.076923     98.076923
Frappuccino® Light Blended Coffee  162.500000     27.500000
Shaken Iced Beverages              114.444444    -20.555556
Signature Espresso Drinks          250.000000    115.000000
Smoothies                          282.222222    147.222222
Tazo® Tea Drinks                   177.307692     42.307692

6. Which Beverage_prep type contains more than the average calories of all drinks? (Hint: to answer this, you’ll have to first figure out what the average calories across all drinks are, and then use that as a filter for the grouped Beverage_prep data).

In [30]:
drinks["avg_calories_category"] = drinks.mean("Calories")

ValueError: No axis named Calories for object type DataFrame

7. Which is the best type of coffee drink to get if you’re worried about consuming too many calories? (Hint: you      can use pd.unique() on a column to get all unique values/levels of that column! Also remember that you can use      isin() to subset with a list)

In [39]:
drinks["Beverage_category"].unique()

array(['Coffee', 'Classic Espresso Drinks', 'Signature Espresso Drinks',
       'Tazo® Tea Drinks', 'Shaken Iced Beverages', 'Smoothies',
       'Frappuccino® Blended Coffee', 'Frappuccino® Light Blended Coffee',
       'Frappuccino® Blended Crème'], dtype=object)

In [42]:
coffee_drinks = drinks[drinks["Beverage_category"].isin(["Coffee", "Classic Espresso Drinks", "Signature Espresso Drinks", "Frappuccino® Blended Coffee", "Light Blended Coffee" ])]

In [44]:
coffee_drinks.loc[coffee_drinks["Calories"].idxmin()]

Beverage_category           Coffee
Beverage             Brewed Coffee
Beverage_prep                Short
Calories                         3
calorie_diff                  -132
Name: 0, dtype: object

8. Filter the dataset drinks so we only take "Classic Espresso Drinks", and save this in a new data frame called      espresso_drinks.

In [51]:
espresso_drinks = drinks[drinks["Beverage_category"] == "Classic Espresso Drinks"]

9. Group your espresso_drinks data frame by the type of Beverage prep, and then find out the mean calories for each    drink group.

In [52]:
espresso_drinks.groupby("Beverage_prep").mean("Calories")

                    Calories  calorie_diff
Beverage_prep
2% Milk              184.375        49.375
Doppio                10.000      -125.000
Grande                15.000      -120.000
Grande Nonfat Milk   150.000        15.000
Short                  5.000      -130.000
Short Nonfat Milk     78.000       -57.000
Solo                   5.000      -130.000
Soymilk              151.250        16.250
Tall                  10.000      -125.000
Tall Nonfat Milk     116.000       -19.000
Venti                 25.000      -110.000
Venti Nonfat Milk    194.000        59.000

10. Get the same grouped mean Calories values as above, but this time sorted in descending order. (Hint: so you're     able to sort the resulting groupby by the 'Calories' column you will want to ensure you get back a dataframe       and not a series)

In [53]:
espresso_drinks.groupby("Beverage_prep").mean("Calories").sort_values("Calories", ascending = False)

                    Calories  calorie_diff
Beverage_prep
Venti Nonfat Milk    194.000        59.000
2% Milk              184.375        49.375
Soymilk              151.250        16.250
Grande Nonfat Milk   150.000        15.000
Tall Nonfat Milk     116.000       -19.000
Short Nonfat Milk     78.000       -57.000
Venti                 25.000      -110.000
Grande                15.000      -120.000
Doppio                10.000      -125.000
Tall                  10.000      -125.000
Short                  5.000      -130.000
Solo                   5.000      -130.000